name: parity
version: git
summary: Fast, light, robust Ethereum implementation
description: |
  Parity's goal is to be the fastest, lightest, and most secure Ethereum
  client. We are developing Parity using the sophisticated and cutting-edge
  Rust programming language. Parity is licensed under the GPLv3, and can be
  used for all your Ethereum needs.

confinement: devmode

apps:
  parity:
    command: parity

parts:
  parity:
    source: .
    plugin: rust
    build-attributes: [no-system-libraries]
    build-packages:
      - libudev-dev
      - libssl-dev
      - make
      - pkg-config
    stage-packages:
      - libssl1.0.0
      - libudev1
      - libstdc++6
